project_id = "wtpvajxekyfekdmypcok"

[functions.analyze-video]
verify_jwt = false

[functions.extract-audio-srt]
verify_jwt = false

[functions.generate-narration]
verify_jwt = false

[functions.generate-podcast]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.team-chatbot]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
