project_id = "wtpvajxekyfekdmypcok"

[functions.analyze-match]
verify_jwt = false

[functions.transcribe-large-video]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.social-publish]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.extract-live-events]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.sync-match]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = false

[functions.arena-chatbot]
verify_jwt = false

[functions.generate-match-report]
verify_jwt = false
